### ISSUE TITLE
Login form should differ from signup form

### ISSUE THREAD

**Issue by stefanomunarini** [alessandrocapra/jammin-react#18]
From a usability point of view, the login form should only contain one password field and the submit button should have Login as a label. 

Signup and Login should have two separate form layouts.

**Comment by mildanor** [comment]
This is because currently sign in it acts both as login and registration  - for the kind of registration style  where you simply link and use your social network account's info to the website when registering. In our case it's your gmail account's profile.

I will be redesigning that page anyway so I will try to make it clearer.

One alternative could be 1) Have login 2) Have fast sign up via google 3) Have a longer version with email verification

Or we keep it as it is but explain the sign up function clearer.

**Comment by mildanor** [comment]
@stefanomunarini It's been changed now. Can I close this issue?
