### ISSUE TITLE
Check responsiveness of the overall design!

### ISSUE THREAD

**Issue by alessandrocapra** [alessandrocapra/jammin-react#21]

**Comment by mildanor** [comment]
@alessandrocapra Note that the new register age isn't responsive at the moment.

**Comment by alessandrocapra** [comment]
@mildanor can you check the overall design? I think it's done now :+1:

**Comment by mildanor** [comment]
@alessandrocapra 

1) Edit profile page is not responsive at all
![screen shot 2016-12-24 at 14 57 29](https://cloud.githubusercontent.com/assets/16984074/21467107/2fae9d96-c9eb-11e6-9b7b-ca278faf3dfc.png)
![screen shot 2016-12-24 at 14 57 39](https://cloud.githubusercontent.com/assets/16984074/21467109/32674e2a-c9eb-11e6-998f-14920f5dc786.png)

2) Can we do something about how these images next to profile are compressed? Doesnt look nice. Alternatively we should put some instruction on how wide pixel wise it is advised that the image should be for the user on the edit profile page, next upload image button so that it doesnt look distorted.
![screen shot 2016-12-24 at 14 56 39](https://cloud.githubusercontent.com/assets/16984074/21467113/43a10032-c9eb-11e6-99ba-4b3bb206966b.png)

3) I cant take screenshots on my phone cause my screenshot button is broken but when I was looking at my or other profile on my phone, the image icon of the first instrument was covering the text of 'My Instruments'
![screen shot 2016-12-24 at 15 05 12](https://cloud.githubusercontent.com/assets/16984074/21467122/8ef951b0-c9eb-11e6-858e-73e34ef4b297.png)




@alessandrocapra I think 1 it's the most important.
